# JOB LEVEL TEMPLATE:
# Used to build XPlatCppSdk
# Reusable
# Meant to be run from the single CppIOSTemplate pipeline (default), or
#   from a multi-pipeline such as publishing (should specify alternate params)

parameters:
- name: ApiSpecSource
  displayName: ApiSpecSource
  type: string
  default: -apiSpecGitUrl https://raw.githubusercontent.com/PlayFab/API_Specs/master/
- name: CommitMessage
  displayName: CommitMessage
  type: string
  default: Automated build from ADO Pipeline
- name: GitDestBranch
  displayName: GitDestBranch
  type: string
  default: doNotCommit
- name: SecureAppleCertName
  displayName: SecureAppleCertName
  type: string
  default: FILLINYOURSELF
- name: SecureAppleCertKeyChain
  displayName: SecureAppleCertKeyChain
  type: string
  default: FILLINYOURSELF
- name: SecureMobileProvisionProfileName
  displayName: SecureMobileProvisionProfileName
  type: string
  default: FILLINYOURSELF
- name: appleTeamId
  displayName: appleTeamId
  type: string
  default: FILLINYOURSELF
- name: iosDeviceId
  displayName: iosDeviceId
  type: string
  default: FILLINYOURSELF
- name: iosSdkVersion
  displayName: iosSdkVersion
  type: string
  default: 14.0
- name: SelfTemplateResource
  displayName: SelfTemplateResource
  type: string
  default: self

jobs:
- job: CppIOSJobTemplate
  steps:
  - bash: echo CppIOSJobTemplate
- job: CppIOSTemplate
  pool: PFMacs
  steps:
  - template: CppIOSStepTemplate.yml
    parameters:
      ApiSpecSource: ${{ parameters.ApiSpecSource }}
      CommitMessage: ${{ parameters.CommitMessage }}
      GitDestBranch: ${{ parameters.GitDestBranch }}
      SecureAppleCertName: ${{ parameters.SecureAppleCertName }}
      SecureAppleCertKeyChain: ${{ parameters.SecureAppleCertKeyChain }}
      SecureMobileProvisionProfileName: ${{ parameters.SecureMobileProvisionProfileName }}
      appleTeamId: ${{ parameters.appleTeamId }}
      iosDeviceId: ${{ parameters.iosDeviceId }}
      iosSdkVersion: ${{ parameters.iosSdkVersion }}
      SelfTemplateResource: ${{ parameters.SelfTemplateResource }}
