# JOB LEVEL TEMPLATE:
# Used to build XPlatCppSdk
# Reusable
# Meant to be run from the single CppMacOsTemplate pipeline (default), or
#   from a multi-pipeline such as publishing (should specify alternate params)

parameters:
- name: ApiSpecSource
  displayName: ApiSpecSource
  type: string
  default: -apiSpecGitUrl https://raw.githubusercontent.com/PlayFab/API_Specs/master/
- name: CommitMessage
  displayName: CommitMessage
  type: string
  default: Automated build from ADO Pipeline
- name: GitDestBranch
  displayName: GitDestBranch
  type: string
  default: doNotCommit
- name: SelfTemplateResource
  displayName: SelfTemplateResource
  type: string
  default: self

jobs:
- job: CppMacOsJobTemplate
  steps:
  - bash: echo CppMacOsJobTemplate
- job: CppMacOsTemplate
  pool: 
  steps:
  - template: CppMacOsStepTemplate.yml
    parameters:
      ApiSpecSource: ${{ parameters.ApiSpecSource }}
      CommitMessage: ${{ parameters.CommitMessage }}
      GitDestBranch: ${{ parameters.GitDestBranch }}
      isVersioned: ${{ parameters.isVersioned }}
      SelfTemplateResource: ${{ parameters.SelfTemplateResource }}
